<script type="text/javascript">
    Validation.add('validate-paynova-govermentid', '<?php echo Mage::Helper("paso")->__("Social security number does not validate")?>', function(v) {
        if (validateGovId(v)) {
            return true;
        }
        return false;
    });
    var paynova_paso_getOrderEmailAdr = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'paso/index/getEmail'?>';
</script>