<?php
/*
 * This file is part of the Paynova Paynovapayment Magento Payment Module, which enables the use of Paynova within the
 * Magento e-commerce platform.
 *
 * @category    Paynova
 * @package     Paynova_Paynovapayment
 */
?>
<?php echo $this->getMethod()->getTitle() ?>
    {{pdf_row_separator}}
<?php echo Mage::helper('paynovapayment')->__('Paynova Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?>
    {{pdf_row_separator}}
