<?php
	if (strlen($code = Mage::getSingleton('adminhtml/config_data')->getStore())) // store level 
	{
		$current_scope = Mage::getModel('core/store')->load($code)->getId();
	}
	elseif (strlen($code = Mage::getSingleton('adminhtml/config_data')->getWebsite())) // website level
	{
		$website_id = Mage::getModel('core/website')->load($code)->getId();
		$current_scope = Mage::app()->getWebsite($website_id)->getDefaultStore()->getId();
	}
	else // default level
	{
		$current_scope = 0;
	}
?>
<button
    type="button"
    class="scalable save"
    onclick="testPaynovaApiCall('<?php echo $current_scope ?>')">
    <span><?php echo $this->__('Test Paynova call'); ?></span>
</button>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js').'paynova/paso/jquery-1.11.1.min.js';?>"></script>
<script>
    var paso_jQuery = jQuery.noConflict(true);
    function testPaynovaApiCall(curscope)
    {
        var MerchantId = paso_jQuery('#paso_setting_merchant_id').val();

        var message_box = paso_jQuery('#paso_test_custom_call_text_message');
        message_box.val('starting test call.. \n sending...');
        //message_box.val(+'<?php echo $this->getUrl('paso/index/');?>');'
        paso_jQuery.ajax({
            type: "POST",
            data: "test",
            url: '<?php echo $this->getUrl('paso/index');?>',
            success: function(data){
                data = jQuery.trim(data);
                if(data.length > 0)
                {
                    $j("#ajaxloader").hide();
                    alert(data);
                }
                else
                {
                    location.href = location.href;
                }
            }
        });
        var customerId = paso_jQuery('#payment_store_credentials_customer_represtantive_id').val();
    }
</script>   
<div id="ajaxloader" style="display:none;padding-top:10px;"> 
    <img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif');?>">
</div>