<?php
/*
 * This file is part of the Paynova paso Magento Payment Module, which enables the use of Paynova within the
 * Magento e-commerce platform.
 *
 *
 * @category    Paynova
 * @package     Paynova_paso
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <?php echo Mage::helper('paso')->__('Payment has not been processed yet.') ?><br />
<?php else: ?>
    <?php echo Mage::helper('paso')->__('Paynova Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?><br />
<?php endif; ?>
