<?php
/*
 * This file is part of the Paynova Aero Magento Payment Module, which enables the use of Paynova within the 
 * Magento e-commerce platform.
 *
 * Copyright (C) 2015  Paynova AB
 * 
 * This module is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    Paynova
 * @package     Paynova_Aero
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <em><?php echo Mage::helper('paynovapayment')->__('You will be redirected to our secure payment page when you place an order.') ?></em>
<?php else: ?>
    <?php echo Mage::helper('paynovapayment')->__('Paynova Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?><br />
<?php endif; ?>
